version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        # CodeDeploy replaces <TASK_DEFINITION> with the ARN of the
        # task definition registered from taskdef.json during this deployment
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "app"
          ContainerPort: 8080
